### PR TITLE
Feat: Added Modal

### PR DESCRIPTION
**Pull request by vinc3nati**

### CODE REVIEW

**Comment by thegeorgenikhil** [comment]
You pushed some wrong files I think

**Review by thegeorgenikhil — CHANGES_REQUESTED** [review]
`.cache` is there by mistake ig

**Review by thegeorgenikhil — APPROVED** [review]

**Comment by thegeorgenikhil** [comment]
Good to merge!

**Review by surajmore98 — APPROVED** [review]
looks all good.

**Pull request merged**
